"""empty message

Revision ID: 8cb73025e82c
Revises: 
Create Date: 2019-06-10 00:49:41.607789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb73025e82c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('socialId', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('sign_date', sa.DateTime(), nullable=True),
    sa.Column('avatar_', sa.String(length=300), nullable=True),
    sa.Column('isCompany', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('subType', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('socialId')
    )
    op.create_index(op.f('ix_user_bio'), 'user', ['bio'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_fullname'), 'user', ['fullname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_of_research', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('updateInterval', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('appId', sa.String(length=100), nullable=True),
    sa.Column('appDev', sa.String(length=100), nullable=True),
    sa.Column('appName', sa.String(length=100), nullable=True),
    sa.Column('algos', sa.Text(), nullable=True),
    sa.Column('ownerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_appDev'), 'research', ['appDev'], unique=False)
    op.create_index(op.f('ix_research_appName'), 'research', ['appName'], unique=False)
    op.create_index(op.f('ix_research_description'), 'research', ['description'], unique=False)
    op.create_index(op.f('ix_research_topic'), 'research', ['topic'], unique=False)
    op.create_table('conducted_research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('researchId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['researchId'], ['research.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('research_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('research_keyword',
    sa.Column('keyword', sa.String(length=80), nullable=False),
    sa.Column('researchId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['researchId'], ['research.id'], ),
    sa.PrimaryKeyConstraint('keyword', 'researchId')
    )
    op.create_table('research_module',
    sa.Column('module', sa.String(length=25), nullable=False),
    sa.Column('researchId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['researchId'], ['research.id'], ),
    sa.PrimaryKeyConstraint('module', 'researchId')
    )
    op.create_table('search_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['research.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('research_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('user_research_permission',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('researchId', sa.Integer(), nullable=False),
    sa.Column('permission', sa.Boolean(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['researchId'], ['research.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'researchId')
    )
    op.create_table('country_interest',
    sa.Column('country', sa.String(length=150), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('interest', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search_trends.id'], ),
    sa.PrimaryKeyConstraint('country', 'search_id')
    )
    op.create_table('day_interest',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('interest', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search_trends.id'], ),
    sa.PrimaryKeyConstraint('date', 'search_id')
    )
    op.create_table('frequency_dictionary',
    sa.Column('keyword', sa.String(length=150), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('conductedResearchId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conductedResearchId'], ['conducted_research.id'], ),
    sa.PrimaryKeyConstraint('keyword')
    )
    op.create_table('news_research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('pos_count_general', sa.Integer(), nullable=True),
    sa.Column('neg_count_general', sa.Integer(), nullable=True),
    sa.Column('analyzerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analyzerId'], ['analyzer.id'], ),
    sa.ForeignKeyConstraint(['id'], ['conducted_research.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('play_store_research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('downloads', sa.String(length=20), nullable=True),
    sa.Column('averageRating', sa.Float(), nullable=True),
    sa.Column('maxReviews', sa.Integer(), nullable=True),
    sa.Column('rateOneCount', sa.Integer(), nullable=True),
    sa.Column('rateTwoCount', sa.Integer(), nullable=True),
    sa.Column('rateThreeCount', sa.Integer(), nullable=True),
    sa.Column('rateFourCount', sa.Integer(), nullable=True),
    sa.Column('rateFiveCount', sa.Integer(), nullable=True),
    sa.Column('analyzerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analyzerId'], ['analyzer.id'], ),
    sa.ForeignKeyConstraint(['id'], ['conducted_research.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related_topic',
    sa.Column('topic', sa.String(length=150), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search_trends.id'], ),
    sa.PrimaryKeyConstraint('topic', 'search_id')
    )
    op.create_table('rising_query',
    sa.Column('query', sa.String(length=150), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search_trends.id'], ),
    sa.PrimaryKeyConstraint('query', 'search_id')
    )
    op.create_table('top_query',
    sa.Column('query', sa.String(length=150), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search_trends.id'], ),
    sa.PrimaryKeyConstraint('query', 'search_id')
    )
    op.create_table('twitter_research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweetsCount', sa.Integer(), nullable=True),
    sa.Column('pos_count', sa.Integer(), nullable=True),
    sa.Column('neg_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['conducted_research.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_article',
    sa.Column('link', sa.String(length=350), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('text', sa.String(length=16000000), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('sentimentScore', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news_research.id'], ),
    sa.PrimaryKeyConstraint('link', 'news_id')
    )
    op.create_table('play_store_review',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('playStoreResearchId', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('sentimentScore', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['playStoreResearchId'], ['play_store_research.id'], ),
    sa.PrimaryKeyConstraint('id', 'playStoreResearchId')
    )
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('twitterResearchId', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('authorUserName', sa.String(length=150), nullable=True),
    sa.Column('authorFullName', sa.String(length=150), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('sentimentScore', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['twitterResearchId'], ['twitter_research.id'], ),
    sa.PrimaryKeyConstraint('id', 'twitterResearchId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet')
    op.drop_table('play_store_review')
    op.drop_table('news_article')
    op.drop_table('twitter_research')
    op.drop_table('top_query')
    op.drop_table('rising_query')
    op.drop_table('related_topic')
    op.drop_table('play_store_research')
    op.drop_table('news_research')
    op.drop_table('frequency_dictionary')
    op.drop_table('day_interest')
    op.drop_table('country_interest')
    op.drop_table('user_research_permission')
    op.drop_table('subscriptions')
    op.drop_table('search_trends')
    op.drop_table('research_module')
    op.drop_table('research_keyword')
    op.drop_table('likes')
    op.drop_table('conducted_research')
    op.drop_index(op.f('ix_research_topic'), table_name='research')
    op.drop_index(op.f('ix_research_description'), table_name='research')
    op.drop_index(op.f('ix_research_appName'), table_name='research')
    op.drop_index(op.f('ix_research_appDev'), table_name='research')
    op.drop_table('research')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_fullname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_bio'), table_name='user')
    op.drop_table('user')
    op.drop_table('revoked_tokens')
    op.drop_table('analyzer')
    # ### end Alembic commands ###
